# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # automatically formats Python code to conform to the PEP 8 style guide
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.3'
    hooks:
      - id: autopep8
  # docstring style formatter
  - repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    rev: 'v0.3.3'
    hooks:
      - id: pep257
  # formatter style formatter
  # if you activate this one, maybe comment the two above
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: '3.8.3'
  #   hooks:
  #     - id: flake8

  # type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
      - id: mypy

  # dead code detection
  - repo: https://github.com/asottile/dead
    rev: v1.3.0
    hooks:
      - id: dead

  # code analysis
  # implementation for https://pypi.org/project/radon/
  - repo: https://github.com/yunojuno/pre-commit-xenon
    rev: ''
    hooks:
      - id: xenon
        args: ["--max-average=A", "--max-modules=C", "--max-absolute=C"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: requirements-txt-fixer
      # - id: trailing-whitespace
      # - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      # - id: check-added-large-files
      # - id: unittest
      #   name: unittest
      #   entry: python -m unittest discover
      #   language: python
      #   "types": [python]
      #   args: ["-p '*test.py'"] # Probably this option is absolutely not needed.
      #   pass_filenames: false
      #   stages: [commit]
