# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # automatically formats Python code to conform to the PEP 8 style guide
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.3'
    hooks:
      - id: autopep8
  # docstring style formatter
  - repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    rev: 'v0.3.3'
    hooks:
      - id: pep257
  # docstring style formatter
  - repo: https://gitlab.com/pycqa/flake8
    rev: ''
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: requirements-txt-fixer
      # - id: flake8
      #   name: flake8
      #   description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
      #   entry: flake8
      #   language: python
      #   types: [python]
      #   require_serial: true

      # - id: trailing-whitespace
      # - id: end-of-file-fixer
      # - id: check-yaml
      # - id: check-added-large-files
      # - id: unittest
      #   name: unittest
      #   entry: python -m unittest discover
      #   language: python
      #   "types": [python]
      #   args: ["-p '*test.py'"] # Probably this option is absolutely not needed.
      #   pass_filenames: false
      #   stages: [commit]
