---
init:
    precommit: pytempl precommit-config --silent
pre-commit:
    commands:
        "*.json":
            - pytempl jsonlint -f
        "*.py":
            - isort
            - pylint --rcfile=.pylintrc
        "*.yaml":
            - yamllint -c .yamllint
        "*.yml":
            - yamllint -c .yamllint
    post-commands:
        - python -m pytest -v --cov=pytempl --cov-report=term --cov-report=html:coverage-report tests/
    pre-commands: []
