init:
  precommit: pytempl precommit --silent
pre-commit:
  commands:
    '*.py':
    - isort
    - yamllint -c .yamllint
    - pytempl jsonlint
    - pylint
    - unittest
  post-commands: []
  pre-commands: []
