pre-commit:
#  run-all: true
  commands:
    '*.json':
    - pytempl jsonlint -f
    '*.py':
    - autopep8 --global-config .pep8
    - isort
#    - pydocstyle --config .pydocstylerc
    - pylint --rcfile=.pylintrc
    - bandit -x tests --ini .bandit
    - radon cc --min B --max E
    '*.yaml':
    - yamllint -c .yamllint
    '*.yml':
    - yamllint -c .yamllint
  post-commands:
  - pytest --cov=pytempl tests/
  pre-commands: []
