init:
  precommit: pytempl precommit --silent
pre-commit:
  commands:
    '*.json':
    - pytempl jsonlint
    '*.py':
    - isort
    - pylint
    '*.yaml':
    - yamllint -c .yamllint
    '*.yml':
    - yamllint -c .yamllint
  post-commands:
  - python -m unittest discover -s tests -p "*_test.py"
  pre-commands: []
