{
    "pre-commit": {
        "pre-commands": [],
        "commands": {
            "*.py": [
                "flake8 --show-source"
            ],
            "*.json": [
                "pytempl jsonlint -f"
            ],
            "*.yaml": [
                "yamllint -c .yamllint"
            ],
            "*.yml": [
                "yamllint -c .yamllint"
            ]
        },
        "post-commands": []
    }
}