{
    "pre-commit": {
        "pre-commands": [],
        "post-commands": [
            "pytest --cov=myproj tests/"
        ],
        "commands": {
            "*.yml": [
                "yamllint -c .yamllint"
            ],
            "*.yaml": [
                "yamllint -c .yamllint"
            ],
            "*.json": [
                "pytempl jsonlint -f"
            ],
            "*.py": [
                "flake8 --show-source"
            ]
        }
    }
}