init:
  precommit: pytempl precommit --silent
pre-commit:
  commands:
    '*.json':
    - pytempl jsonlint
    '*.py':
    - isort
    - pylint
    - ''
    '*.yaml':
    - yamllint -c .yamllint
    '*.yml':
    - yamllint -c .yamllint
  post-commands: []
  pre-commands: []
